### ISSUE TITLE
Error with worlds

### ISSUE THREAD

**Issue by ItzBulkDev** [williamtdr/Katana#10]
There is a bug with worlds in which spawnpoints are messed up and chunks

**Comment by ItzBulkDev** [comment]
How is this invalid? worlds are legit messed up

**Comment by xxFlare** [comment]
Please read the readme before you open up invalid errors.

1: Katana does not generate worlds.
2. Only Anvil and MCregion are supported (MCRegion recommended).

Also this is not made for survival or creative servers.

**Comment by Gamecrafter** [comment]
@xxFlare Please make sure you've read it correctly. Nowhere in the README does it say that Katana doesn't generate worlds. And yes, this isn't recommended for the typical survival/creative server, aka vanilla server.

**Comment by PEMapModder** [comment]
@ItzBulkDev are you unable to reproduce the issue if you directly change the Katana build to PocketMine build on the `mcpe-0.12` branch?
