### ISSUE TITLE
invisible tiles

### ISSUE THREAD

**Issue by Creeperface01** [williamtdr/Katana#20]

**Comment by Gamecrafter** [comment]
@Creeperface01 This is the kind of issue I find useless(**very** useless). You say "invisible tiles", that's too vague. And you don't even provide information about it. Don't spam issues and pull requests.

**Comment by iVertx** [comment]
The information is: wonder a HungerGames map... Without chests... Wonder a hub.... Without signs... Thats exactly what is happening with katana, and Tile->spawnToAll(); does not seem to solve that problem, @Creeperface01, @Gamecrafter Is right, provide more information when opening issues, and @Gamecrafter, try to be a bit less stupid with everyone, that's annoying :+1:

**Comment by Gamecrafter** [comment]
@iVertx :+1: He's the one that opened an issue without giving a lot of details. I make sure they don't do it again.

**Comment by Creeperface01** [comment]
if I knew where is the bug, I would fix it and i would not open an issue ;) and tile is spawned to client because just texture is invisible. I can see particles or i can not go trough.
