### ISSUE TITLE
config

### ISSUE THREAD

**Issue by SavionLegendZzz** [williamtdr/Katana#28]
ok so if i disable/enable a option in the config it dosent work

**Comment by williamtdr** [comment]
Please provide some details in formal English then try again :P

**Comment by SavionLegendZzz** [comment]
ok let me re try. hello there is an issue with Katana where if you edit Katana.yml the settings do not active ex: if i change save-player-data it does not work

**Comment by PEMapModder** [comment]
Please define `does not work`.

**Comment by SavionLegendZzz** [comment]
if i change chuck-cache to disable it dosent disable it

**Comment by PEMapModder** [comment]
@SavionLegendZzz is the value in katana.yml overwritten?

**Comment by SavionLegendZzz** [comment]
no just dosent apply
