### ISSUE TITLE
No Resources in SPL

### ISSUE THREAD

**Issue by ItzBulkDev** [williamtdr/Katana#9]
ThreadedFactory.php cannot be found within src/spl and causes the startup to fail

**Comment by linuzo** [comment]
Download it from the SPL shortcut in the source....  Use the zip to download and extract because cloning with git misses it for some reason.. It's not a bug on this software though..

**Comment by linuzo** [comment]
You have to get SPL and Raklib from Pocketmine github in order to compile this software.. Just FYI

**Comment by KnownUnown** [comment]
`git pull && git submodule init && git submodule update`

**Comment by ItzBulkDev** [comment]
ThreadFactory.php isn't in pocketmine SPL.

**Comment by PEMapModder** [comment]
Or simply:

```bash
git clone https://github.com/williamtdr/Katana.git
```

**Comment by KnownUnown** [comment]
>.>
https://github.com/PocketMine/PocketMine-SPL/commit/82034afea351b0dbf8b1f9ad41cde9b9de3e1da6
Pull an earlier version!

**Comment by ItzBulkDev** [comment]
I know receive the following error:

Fatal error: Uncaught exception 'RuntimeException' with message 'pthreads detected an attempt to connect to a Threaded which has already been destroyed' in C:\Users\Sony user\Desktop\Multicraft (1)\Multicraft\multicraft\jar\PocketMine-MP_1.6dev\src\spl\BaseClassLoader.php:45
Stack trace:
#0 C:\Users\Sony user\Desktop\Multicraft (1)\Multicraft\multicraft\jar\PocketMine-MP_1.6dev\src\spl\BaseClassLoader.php(45): BaseClassLoader::addPath()
#1 C:\Users\Sony user\Desktop\Multicraft (1)\Multicraft\multicraft\jar\PocketMine-MP_1.6dev\src\pocketmine\PocketMine.php(109): BaseClassLoader->addPath('C:\\Users\\Sony u...')
#2 {main}
  thrown in C:\Users\Sony user\Desktop\Multicraft (1)\Multicraft\multicraft\jar\PocketMine-MP_1.6dev\src\spl\BaseClassLoader.php on line 45
bin\php\php.exe: Exit 255


@KnownUnown

**Comment by KnownUnown** [comment]
just....
`git clone --recursive https://github.com/williamtdr/Katana`

**Comment by ItzBulkDev** [comment]
@KnownUnown I am using windows

**Comment by linuzo** [comment]
Here --> https://github.com/PocketMine/PocketMine-SPL/commit/82034afea351b0dbf8b1f9ad41cde9b9de3e1da6

Copy and paste it to a file
.

**Comment by ItzBulkDev** [comment]
@linuzo again, I receive this message when doing that

I know receive the following error:

Fatal error: Uncaught exception 'RuntimeException' with message 'pthreads detected an attempt to connect to a Threaded which has already been destroyed' in C:\Users\Sony user\Desktop\Multicraft (1)\Multicraft\multicraft\jar\PocketMine-MP_1.6dev\src\spl\BaseClassLoader.php:45
 Stack trace:
 #0 C:\Users\Sony user\Desktop\Multicraft (1)\Multicraft\multicraft\jar\PocketMine-MP_1.6dev\src\spl\BaseClassLoader.php(45): BaseClassLoader::addPath()
#1 C:\Users\Sony user\Desktop\Multicraft (1)\Multicraft\multicraft\jar\PocketMine-MP_1.6dev\src\pocketmine\PocketMine.php(109): BaseClassLoader->addPath('C:\Users\Sony u...')
#2 {main}
 thrown in C:\Users\Sony user\Desktop\Multicraft (1)\Multicraft\multicraft\jar\PocketMine-MP_1.6dev\src\spl\BaseClassLoader.php on line 45
 bin\php\php.exe: Exit 255

**Comment by linuzo** [comment]
OK here then.   ---->   http://www.megafileupload.com/5e0m/pocketmine-spl-old.zip

My SPL folder zipped up and works fine..  NO issues..

**Comment by ItzBulkDev** [comment]
I've gotten it fixed thanks for the fast responses :)

**Comment by ItzBulkDev** [comment]
Also is there a Multicraft CONF for this yet?

**Comment by anoymous-github** [comment]
hi,i'm the person who is building the pmmp server little bit diffrently.
user "linuzo",i'm having similar problem like user "itzbulkdev",seems the file link (http://www.megafileupload.com/5e0m/pocketmine-spl-old.zip) has been dead..
so what i want to request is, could you reupload that file,please?sorry for my bad english o u o;;

**Comment by linuzo** [comment]
https://github.com/PocketMine/PocketMine-SPL/tree/82034afea351b0dbf8b1f9ad41cde9b9de3e1da6
